/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lexico;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author CARLOS JESUS
 */
public class Vista_Principal extends javax.swing.JFrame {
    
    int xMouse, yMouse;
    DefaultTableModel modelo = new DefaultTableModel();

      //ArrayList<Token> lista_token = new ArrayList();
    public Vista_Principal() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        
        modelo.addColumn("FILA");
        modelo.addColumn("COLUMNA");
        modelo.addColumn("LEXEMA");
        modelo.addColumn("TOKEN");
        modelo.addColumn("TIPO");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_resultados = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_editor = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_analizar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_analizarTexto = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JPanel();
        txt_limpiar = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        btn_exit = new javax.swing.JPanel();
        txt_exit = new javax.swing.JLabel();
        btn_min = new javax.swing.JPanel();
        txt_min = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setPreferredSize(new java.awt.Dimension(1660, 630));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_resultados.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 12)); // NOI18N
        tbl_resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tbl_resultados);

        fondo.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 570, 320));

        txt_editor.setColumns(20);
        txt_editor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        txt_editor.setRows(5);
        jScrollPane1.setViewportView(txt_editor);

        fondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 400, 320));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ANALIZADOR LÉXICO");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel4.setText("Tokens encontrados:");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 220, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel6.setText("Código:");
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 80, -1));

        btn_analizar.setBackground(new java.awt.Color(36, 113, 163));
        btn_analizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/analizar.png"))); // NOI18N
        btn_analizar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        txt_analizarTexto.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        txt_analizarTexto.setForeground(new java.awt.Color(255, 255, 255));
        txt_analizarTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_analizarTexto.setText("Analizar");
        txt_analizarTexto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txt_analizarTexto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_analizarTextoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_analizarTextoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_analizarTextoMouseExited(evt);
            }
        });
        btn_analizar.add(txt_analizarTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 140, 60));

        fondo.add(btn_analizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 180, -1, 80));

        btn_limpiar.setBackground(new java.awt.Color(36, 113, 163));
        btn_limpiar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_limpiar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        txt_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        txt_limpiar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_limpiar.setText("Limpiar");
        txt_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_limpiarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_limpiarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_limpiarMouseExited(evt);
            }
        });
        btn_limpiar.add(txt_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 140, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icono/imagen_limpiar.png"))); // NOI18N
        btn_limpiar.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 60));

        fondo.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 290, -1, 80));

        header.setBackground(new java.awt.Color(41, 128, 185));
        header.setForeground(new java.awt.Color(127, 179, 213));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_exit.setBackground(new java.awt.Color(229, 231, 234));
        btn_exit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_exit.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        txt_exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_exit.setText("X");
        txt_exit.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        txt_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_exitMouseExited(evt);
            }
        });
        btn_exit.add(txt_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        header.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 50, 30));

        btn_min.setBackground(new java.awt.Color(229, 231, 233));
        btn_min.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_min.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        txt_min.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_min.setText("-");
        txt_min.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        txt_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_minMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_minMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txt_minMouseExited(evt);
            }
        });
        btn_min.add(txt_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 30));

        header.add(btn_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 0, 50, 30));

        fondo.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, -1));

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_exitMouseClicked
        if(0 == Preguntar_Salir()){
            System.exit(0);
        }
    }//GEN-LAST:event_txt_exitMouseClicked

    private void txt_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_exitMouseEntered
        btn_exit.setBackground(Color.red);
        txt_exit.setForeground(Color.white);
    }//GEN-LAST:event_txt_exitMouseEntered

    private void txt_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_exitMouseExited
        btn_exit.setBackground(new Color(229, 231, 233));
        txt_exit.setForeground(Color.black);
    }//GEN-LAST:event_txt_exitMouseExited

    private void txt_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_minMouseClicked
        setExtendedState(ICONIFIED);
    }//GEN-LAST:event_txt_minMouseClicked

    private void txt_minMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_minMouseEntered
        btn_min.setBackground(Color.blue);
        txt_min.setForeground(Color.white);
    }//GEN-LAST:event_txt_minMouseEntered

    private void txt_minMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_minMouseExited
        btn_min.setBackground(new Color(229, 231, 233));
        txt_min.setForeground(Color.black);
    }//GEN-LAST:event_txt_minMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void txt_analizarTextoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_analizarTextoMouseClicked
        ArrayList<Token> lista_token = new ArrayList();
        new analizador (lista_token).analizar(txt_editor.getText());
        
        //rellenar tabla
        tbl_resultados.setModel(modelo);
        darleFormaALaTabla(tbl_resultados);
        for(int i=0; i<lista_token.size(); i++){
            Vector<Object> fila = new Vector<>();
            
            fila.add(lista_token.get(i).getFila());
            fila.add(lista_token.get(i).getColumna());
            fila.add(lista_token.get(i).getLexema());
            fila.add(lista_token.get(i).getNumero_token());
            fila.add(lista_token.get(i).getTipo());
            
            modelo.addRow(fila);
        }
    }//GEN-LAST:event_txt_analizarTextoMouseClicked

    private void txt_analizarTextoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_analizarTextoMouseEntered
        btn_analizar.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_txt_analizarTextoMouseEntered

    private void txt_analizarTextoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_analizarTextoMouseExited
        btn_analizar.setBackground(new Color(36, 113, 163));
    }//GEN-LAST:event_txt_analizarTextoMouseExited

    private void txt_limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_limpiarMouseClicked
        limpiar();
    }//GEN-LAST:event_txt_limpiarMouseClicked

    private void txt_limpiarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_limpiarMouseEntered
        btn_limpiar.setBackground(new Color(21, 67, 96));
    }//GEN-LAST:event_txt_limpiarMouseEntered

    private void txt_limpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_limpiarMouseExited
        btn_limpiar.setBackground(new Color(36, 113, 163));
    }//GEN-LAST:event_txt_limpiarMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tbl_resultados.setModel(modelo);
    }//GEN-LAST:event_formWindowOpened
    
    public static int Preguntar_Salir(){
        return JOptionPane.showOptionDialog(null, "Estas a punto de salir "
                + "¿Estas Seguro?", "¿Desea Salir?", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Si","No"}, 0);
    }
    
    private void limpiar(){
        txt_editor.setText("");
        modelo.setRowCount(0);
        
    }
    
    public void darleFormaALaTabla(JTable tabla){
        tabla.getColumnModel().getColumn(0).setPreferredWidth(2);
        tabla.getColumnModel().getColumn(1).setPreferredWidth(2);
        tabla.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabla.getColumnModel().getColumn(3).setPreferredWidth(10);
        tabla.getColumnModel().getColumn(4).setPreferredWidth(100);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_analizar;
    private javax.swing.JPanel btn_exit;
    private javax.swing.JPanel btn_limpiar;
    private javax.swing.JPanel btn_min;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_resultados;
    private javax.swing.JLabel txt_analizarTexto;
    private javax.swing.JTextArea txt_editor;
    private javax.swing.JLabel txt_exit;
    private javax.swing.JLabel txt_limpiar;
    private javax.swing.JLabel txt_min;
    // End of variables declaration//GEN-END:variables
}
